language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_install:
  - composer self-update
install:
  - composer install
before_script:
  - phpenv config-add phpconfig.ini
script:
  - vendor/bin/codecept run
notfications:
  email:
    on_success: always
    on_failure: always
